In [1]:
import numpy as np

In [2]:
from keras.models import Model
from keras.layers import Input, Dense, Activation
from keras.activations import sigmoid, softmax, tanh, linear

Using TensorFlow backend.


In [3]:
inp = Input(shape=(25,), name = 'inp')
dense1 = Dense(50, activation = sigmoid)(inp)
outp_qvalues = Dense(25, activation = linear, name = 'outp_qvalues')(dense1)
outp_probs = Activation(activation = softmax, name = 'outp_probs')(outp_qvalues)

In [4]:
model = Model(inputs=inp, outputs=[outp_qvalues, outp_probs])

In [5]:
losses = {
    "outp_qvalues": "mean_squared_error"
}

In [6]:
model.compile(optimizer='sgd', loss=losses, metrics=['accuracy'])

C:\Users\yusacheva\AppData\Local\conda\conda\envs\university\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Output "outp_probs" missing from loss dictionary. We assume this was done on purpose, and we will not be expecting any data to be passed to "outp_probs" during training.
  """Entry point for launching an IPython kernel.


In [7]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inp (InputLayer)             (None, 25)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 50)                1300      
_________________________________________________________________
outp_qvalues (Dense)         (None, 25)                1275      
_________________________________________________________________
outp_probs (Activation)      (None, 25)                0         
Total params: 2,575
Trainable params: 2,575
Non-trainable params: 0
_________________________________________________________________


In [8]:
from keras.models import save_model

In [9]:
# model.save("first.h5")

In [10]:
a = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
a.shape

(1, 25)

In [12]:
y = model.predict(a)

In [13]:
y

[array([[-8.96071345e-02, -6.57381475e-01, -4.15291935e-01,
          2.37016395e-01,  4.41862673e-01, -9.94500369e-02,
          1.54145464e-01, -6.19319439e-01,  2.41044626e-01,
          2.79939473e-01, -9.08659697e-02,  1.01639640e+00,
          3.73314112e-01, -5.09077907e-01,  2.15284914e-01,
          1.03858745e+00, -1.21128120e-01, -1.23246685e-02,
         -3.85141373e-01, -6.97715282e-02, -9.00093913e-01,
         -6.92906976e-01,  1.00707030e+00, -5.12834638e-04,
         -4.55411702e-01]], dtype=float32),
 array([[0.03187729, 0.01806759, 0.02301645, 0.04419083, 0.05423702,
         0.03156506, 0.04067633, 0.01876853, 0.0443692 , 0.04612894,
         0.03183719, 0.09634133, 0.05064371, 0.02095596, 0.04324086,
         0.09850314, 0.03088816, 0.03443854, 0.02372097, 0.03251591,
         0.01417397, 0.01743699, 0.09544701, 0.03484773, 0.02211131]],
       dtype=float32)]

In [22]:
kk = y[1]

In [47]:
kk

array([[0.03187729, 0.01806759, 0.02301645, 0.04419083, 0.05423702,
        0.03156506, 0.04067633, 0.01876853, 0.0443692 , 0.04612894,
        0.03183719, 0.09634133, 0.05064371, 0.02095596, 0.04324086,
        0.09850314, 0.03088816, 0.03443854, 0.02372097, 0.03251591,
        0.01417397, 0.01743699, 0.09544701, 0.03484773, 0.02211131]],
      dtype=float32)

In [48]:
ind = np.argmax(kk) + 1

In [49]:
a_x = ind % 5
a_y = int(ind / 5)

In [50]:
a_x

1

In [51]:
a_y

3

In [57]:
kk[0][ind - 1] = 0

In [58]:
np.argmax(kk)

11

In [25]:
kkk = [3, 4, 1, 0]

In [26]:
mm = np.array(kkk)

In [31]:
np.argmax(kkk)

1

In [19]:
b = np.zeros((1, 25))

In [20]:
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [59]:
from keras.models import load_model

In [60]:
l_model = load_model('first.h5')

C:\Users\yusacheva\AppData\Local\conda\conda\envs\university\lib\site-packages\keras\engine\saving.py:312: UserWarning: Output "outp_probs" missing from loss dictionary. We assume this was done on purpose, and we will not be expecting any data to be passed to "outp_probs" during training.
  sample_weight_mode=sample_weight_mode)


In [61]:
l_model.predict(a)

[array([[-0.34292877, -0.43087977, -0.37743697, -0.3891447 ,  1.1803552 ,
         -1.1622374 ,  0.56889254, -0.27675983, -0.08712399,  1.6129327 ,
          0.19450429,  0.24993993, -0.7557677 , -0.84845585,  0.350111  ,
         -0.5962233 ,  0.7107175 ,  0.14006963, -0.6233464 ,  0.22597387,
         -0.43275866, -0.30041355, -0.40994394, -0.47744262,  0.09003142]],
       dtype=float32),
 array([[0.02459134, 0.02252089, 0.02375721, 0.02348069, 0.11280701,
         0.0108383 , 0.0612042 , 0.02627357, 0.03175974, 0.17386097,
         0.04209073, 0.04448994, 0.01627378, 0.01483319, 0.0491774 ,
         0.01908877, 0.07053018, 0.03986078, 0.01857798, 0.04343637,
         0.02247862, 0.02565939, 0.02299736, 0.02149629, 0.0379153 ]],
       dtype=float32)]